services:
  dev:
    image: gpu-${USER}
    container_name: gpu-${USER}
    build:
      dockerfile: gpu.Dockerfile
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${https_proxy}
        HOME: ${HOME}
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        WORKSPACE: ${WORKSPACE}
      network: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    shm_size: '24G'
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - DISPLAY
      - XDG_RUNTIME_DIR=/tmp/runtime-${USER}
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
      - https_proxy
      - http_proxy
      - no_proxy
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - type: bind
        source: ${HOME:?HOME has to be set}
        target: ${HOME}
      - type: bind
        source: /etc/ssl/certs
        target: /etc/ssl/certs
      - type: bind
        source: /mnt/hdd
        target: /mnt/hdd
      - type: bind
        source: /tmp
        target: /tmp
